### PR TITLE
added file header to browser/common.js and added license file

### PR DESCRIPTION
**Pull request by zebastian**
LGPL License taken from here: https://www.gnu.org/licenses/lgpl.txt
second commit fixes for correct lgpl license, see commit for details

### CODE REVIEW

**Comment by timurhai** [comment]
Hi.
Wait a while!
I am busy and thinking up this )

**Comment by zebastian** [comment]
Sure,
btw in Mandelbulber we separate the copyright from the authors and write to every file, who authored it.
example: https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/src/algebra.hpp
```
/**
 * Mandelbulber v2, a 3D fractal generator       ,=#MKNmMMKmmßMNWy,
 *                                             ,B" ]L,,p%%%,,,§;, "K
 * Copyright (C) 2014-17 Mandelbulber Team     §R-==%w["'~5]m%=L.=~5N
...
 * Authors: Krzysztof Marczak (buddhi1980@gmail.com), Robert Pancoast (RobertPancoast77@gmail.com)
 *
...
 */
```
This makes it easy to contact a person who might be responsible for a file. Issues can directly be assigned to the author.

**Comment by timurhai** [comment]
Hi.
Sorry for a delay.

Copyright should not be set to me. As some files (parts) are completely not mine.
Also remind that we should keep some already existing headers for files from other projects.
And i think that logo drawings should be very cool, or should not be at all :)
For now i can't imagine how to type CGRU or AFANASY to look awesome.

**Comment by zebastian** [comment]
Sure, the files which are completely taken from somewhere else, should stay untouched.
What about the files written in the project? Are these copyright of you / copyright of the authors / copyright of "CGRU team"?

about logo: how about that:
```
  .g8  "bgd    .g  ""bgd  `7MM"  Mq. `7MMF'   `7MF'
.dP'     `M  .dP'     `M    MM   `MM.  MM       M
dM'       `  dM'       `    MM   ,M9   MM       M
MM           MM             MMm  M9    MM       M
MM.          MM.    `7MMF'  MM   M.    MM       M
`Mb.     ,d  `Mb.     MM    MM   `Mb.  YM.     ,M
  `"b  md'     `"  mmdPY  .JMML  .JMM.  `bm  md"'

          A    F    A    N    A    S    Y
```
btw, basic font taken from here:
http://patorjk.com/software/taag/#p=display&f=Georgia11&t=CGRU

**Comment by zebastian** [comment]
round two:

```
/** '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' *\
 *    .g8  "bgd    .g  ""bgd  `7MM"  Mq. `7MMF'   `7MF'             This file is part of CGRU
 *  .dP'     `M  .dP'     `M    MM   `MM.  MM       M      - The Free And Open Source CG Tools Pack.
 *  dM'       `  dM'       `    MM   ,M9   MM       M   CGRU is licensed under the terms of LGPLv3, see files   
 *  MM           MM             MMm  M9    MM       M     COPYING and COPYING.lesser inside of this folder.
 *  MM.          MM.    `7MMF'  MM   M.    MM       M            Project-Homepage: http://cgru.info
 *  `Mb.     ,d  `Mb.     MM    MM   `Mb.  YM.     ,M        Sourcecode: https://github.com/CGRU/cgru
 *    `"b  md'     `"  mmdPY  .JMML  .JMM.  `bm  md"'
 *                                                                       Copyright © 2012-17 by The CGRU team
 *                                                            Authors: Timur Hairulin (cgruafanasy@gmail.com)
 * common.js - common js stuff for the afanasy webpage
 * 
 * This file contains common structures, misc formatting and user permission functions used throughout
 * all afanasy/browser/*.js files. 
 * ....................................................................................................... */
```

**Comment by timurhai** [comment]
I prefer something with almost the same characters, like:
http://patorjk.com/software/taag/#p=display&f=Big&t=CGRU
http://patorjk.com/software/taag/#p=display&f=Slant&t=CGRU
http://patorjk.com/software/taag/#p=display&f=Small&t=CGRU
http://patorjk.com/software/taag/#p=display&f=Small%20Slant&t=CGRU
Also authors section should be updated from repo periodically. As each file has own authors. Better to skip it at all.
Email for contacts should be also skipped as on sites are various contacts information.

**Comment by zebastian** [comment]
how about that:
```
/** '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' *\  
 *        .NN.        _____ _____ _____  _    _                 This file is part of CGRU
 *        hMMh       / ____/ ____|  __ \| |  | |       - The Free And Open Source CG Tools Pack.       
 *       sMMMMs     | |   | |  __| |__) | |  | |  CGRU is licensed under the terms of LGPLv3, see files     
 * <yMMMMMMMMMMMMMMy> |   | | |_ |  _  /| |  | |    COPYING and COPYING.lesser inside of this folder. 
 *   `+mMMMMMMMMNo` | |___| |__| | | \ \| |__| |          Project-Homepage: http://cgru.info
 *     :MMMMMMMM:    \_____\_____|_|  \_\\____/        Sourcecode: https://github.com/CGRU/cgru
 *     dMMMdmMMMd
 *    -Mmo.  -omM:                                                      Copyright © 2012-17 by The CGRU team    
 *    '          '  
 * common.js - common js stuff for the afanasy webpage
 *
 * This file contains common structures, misc formatting and user permission functions used throughout
 * all afanasy/browser/*.js files. 
 * ....................................................................................................... */
```

**Comment by timurhai** [comment]
Great!

**Comment by zebastian** [comment]
@timurhai as a team developer i have direct write access to your repository and can merge or push directly without your approval. If this was intended, thanks for your confidence :-)

**Comment by timurhai** [comment]
Try to use branches for tests/something new.
If you want to discuss some commit or not sure in it use pull requests.
Such errors as typos, small enhancements that keeps compatibility you can push yourself.
Later i should think up some rules for developers and put them in readme.

**Comment by zebastian** [comment]
OK, makes sense. next refactoring is already in its own branch: https://github.com/zebastian/cgru/tree/clang-format
When you approved this pull request here i can add the other refactorings to js files directly, as they will just stick directly to the format already defined in the clang-format file (when there are controversial points about the format, its easy to change the .clang-format file and reapply the code format).

**Comment by timurhai** [comment]
btw
Can you tell your code editor to not to apply restyling to all cpp files?
Header can be added to cpp files (that has no one).
But i prefer to keep history.
Can you apply styling on (around) changes only?
Javascript and other languages can all be reformatted at once (it needed).

**Comment by zebastian** [comment]
I use clion (jetbrains IDE) and qtcreator for cpp and js development
sometimes also gedit for simple files.
The coding style i apply directly with clang cli program
```
$ clang-format -i -style=file work.js
```
I can port the  script from mandelbulber to cgru which does this automated for the whole code base:
- add and modify file header
- refactor with clang-format
Can i place this maintenance script into ./utilities/maintenance?
I can setup the script, to only run on recently modified (not yet commited changed) files. This way the git-log history is not changed for all cpp files at once.
Is this what you had in mind?

**Comment by timurhai** [comment]
Yes you can.
Yes, i had mean this.

**Pull request merged**
