### PR TITLE
Updates to Fusion and ``REZ_USED_RESOLVE``

### PR DESCRIPTION
**Pull request by eoyilmaz**
* [Fusion] Introducing the new Job submission UI that is using the modern Python API instead of the ``afcmd.py``.
* [CGRU] Implemented the suggested use of ``REZ_USED_RESOLVE`` in #550

### CODE REVIEW

**Comment by timurhai** [comment]
Hi!
I can't test it, as we are not using REZ.

**Comment by Anti-Distinctlyminty** [comment]
Tested and confirmed with Houdini. The res environment:

```
echo %REZ_USED_RESOLVE%
platform-windows arch-AMD64 afanasy_settings afanasy-3.3.0 houdini-19.0.561 redshift-3.0.67
```

And using the same environment to launch Keeper, results in the following processed task command:

```
rez-env platform-windows arch-AMD64 afanasy_settings afanasy-3.3.0 houdini-19.0.561 redshift-3.0.67 -- hrender_af -s 4 -e 4 --by 1 -t "_current_" "C:/Users/luke/AppData/Local/Temp/houdini_temp/test-afanasy1.1121-125322-655.hip" "/out/Redshift_ROP1"
```

All frame successfully rendered.

**Comment by eoyilmaz** [comment]
@timurhai should we merge this PR?

**Comment by timurhai** [comment]
I think we can.

**Pull request merged**
