### PR TITLE
Add Preview Pending Approval to the CGRU Blender Addon

### PR DESCRIPTION
**Pull request by g-LuL**
I simply add the ppa attribute to the Blender Addon.

### CODE REVIEW

**Comment by g-LuL** [comment]
Oups, my commit log isn't very clear... I've never commit on github so if it's possible to change it, I would like to know how.
Or if you can modify it, don't hesitate !
Thanks

**Comment by mifth** [comment]
you can make another pull request.

**Comment by mifth** [comment]
did you test this feature?

**Comment by g-LuL** [comment]
Yes I've tested it.
Ok for the New Pull Request. I'm a beginner at this so i need a little time...

**Comment by timurhai** [comment]
merged
now we can test it in the master branch

**Comment by timurhai** [comment]
I tested. It works!

**Comment by g-LuL** [comment]
Wonderful ! 
;)

**Comment by mifth** [comment]
great!

**Pull request merged**
