### PR TITLE
Appended flags

### PR DESCRIPTION
**Pull request by yannci**
To use the feature to append blocks and tasks to already running jobs it might come in handy to query 
from a job if it has appended blocks or from a block if it has appended tasks. Therefore this PR adds flags 
to the job and blockdata to specify this. 

It further extends the python API to check if the flag is set. The afcommon module did not provide job flags for now that are added.
The corresponding setter are treating the 'appendedtasks' and 'appendedblocks' as read only.

Additionally there is a small fix regarding the 'isNumeric' and 'appendBlocks' functions in afcmd, that did not return the correct flag value and used a 'False' check that did not work correctly in python.

Please review and let me know what you think about this additions.

Thanks,
Yannic

### CODE REVIEW

**Comment by timurhai** [comment]
Hi!
Can you explain the situation where such flag is needed?
Appending is more looks like some event, not like some permanent state.

**Comment by timurhai** [comment]
ps
I still have not used appending in production and even have not test how it works.
When it was under develop, i was very busy with pools & tickets, and spent very much time with it.
Now i have lots of work to finish till the NY.
So, probably, i will review appending blocks/tasks generally after the NY.

**Comment by lithorus** [comment]
I'm not a fan of changing the isNumeric() to change return type in certain situations.

**Comment by yannci** [comment]
> Hi!
> Can you explain the situation where such flag is needed?
> Appending is more looks like some event, not like some permanent state.

Of course! You're absolutely right, appending a task or block is an event per se. But we think asking the job or block if it has something appended might come in handy. We can append tasks or blocks to a job although it's state is DON and then it's reset to RUN. Any script that runs as soon as a Job is done might need to be delayed. This delay can be triggered by asking for appended blocks/tasks. With this query one can also implement signal/slots in Qt etc if needed.

But these are just cases I imagined. Appending tasks is also needed to implement SideFx PDG into afanasy and that might need to know this as well. I want to use it in a python UI that should run an update loop for jobs and blocks on append. And this update loop can be resticted to jobs or blocks that have these flags set.

Hope this was understandable and made the point more clear. If not, don't hesitate to reach out to me!

Thanks,
Yannic

**Comment by yannci** [comment]
> I'm not a fan of changing the isNumeric() to change return type in certain situations.
> (or I just misunderstand what's happening in the checkBlockFlag function)

My reason to rework the 'isNumeric' here is the following: When creating a block with af.Block it is initially a non numeric block.
After sending the job to the server and retrieving it with the afcmd module the Block for me is set to be numeric if using the bitshift and bool casting approach used here. And therefore tasks never got appended. I did not find the reason in the server code yet or maybe this is a python thing. To come over this problem I used the already existing 'checkBlockFlags' function in the afcommon module.

You're right, the return value from this is either 0 or 1 not a boolean anymore and because of this the 'if is False' clause did not work anymore and I used the more pythonic version 'if not'. The return value could be explicitly casted to boolean afterwards anyhow.

Hope this helps your understanding. If not let me know and we can discuss this even further. Can you tell me a case where you'd like to have a boolean return value instead of 0 or 1?

**Comment by lithorus** [comment]
That would break existing code for no reason.

E.g. if you have code going :
```
if block.isNumeric() is True:
    doStuff()
```

**Comment by yannci** [comment]
> That would break existing code for no reason.
> 
> E.g. if you have code going :
> 
> ```
> if block.isNumeric() is True:
>     doStuff()
> ```

I understand where you are coming from. But using the API for appendingBlocks does not work this way because block.isNumeric() returns True although its false. At least on my side.

Please test and prove me wrong. Here athe steps I did with the current implementation:

1. create a job via af.Job()
2. add a block with a task
3. send the job to the server
4. get the job via afcmd.getJob()
5. retrieve the block from the job
6. append a task via appendTask()

This tasks is never appended on my side because the 
`if block.isNumeric() is False:`
is never False after getting the Job from the server.

If I am doing something wrong please tell me this. I don't mind reverting the changes and take them out from the PR if this works correctly!

Thank you

**Comment by sebastianelsner** [comment]
I would propose that isNumeric just returns a boolean instead 0 or 1 (which is what the check flags function returns). All should be happy then.

**Comment by yannci** [comment]
> I would propose that isNumeric just returns a boolean instead 0 or 1 (which is what the check flags function returns). All should be happy then.

Would be fine for me. What do the others think?

**Comment by timurhai** [comment]
I am not using that part of API, but my opinion, that `isFunction()` should return boolean.
We can add the same `getFunction()` that will return a number.

**Comment by yannci** [comment]
I have updated the code to return a boolean from isNumeric as it's been before.

**Comment by timurhai** [comment]
Hi!
So, what we should do with this issue?

**Comment by sebastianelsner** [comment]
Hi, @yannci fixed the things @lithorus wanted. So I guess its ready for merge.

**Pull request merged**
