### PR TITLE
Introduce automatic reconnection of old renders to new server

### PR DESCRIPTION
**Pull request by eliemichel**
When the server goes down, and later on up again, the renders keep on running their
task and claim them against the new server.

This require not to mess up with the render info stored in persistent storage
(/var/tmp/afanasy or the likes), otherwise the behavior is undefined.

Note: we may not need to have a different state of lost connection (and so we could
either drop or set to a very high value m_connection_lost_count).

@timurhai  threadrunmsgcase.cpp:42, I commented a line that caused a deadlock. But is it
safe to use rendersIt.getRender() then? How else could I do? Also, I need you to check
how hack you find the new Block::reconnect()

I will complete this PR as soon as you'd ask for it!

### CODE REVIEW

**Comment by eliemichel** [comment]
Sorry, this also include a bunch of renaming of `printf` -> `AF_LOG`.

**Comment by timurhai** [comment]
Hi! Great! I'll check everything.

In the main "run" thread all containers are already write-locked:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/threadrun.cpp#L74

So we should lock containers only in this function:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/threadprocessmsgcase.cpp#L31
And also locking is performed at job registration:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/jobcontainer.cpp#L56

Note, if you need to lock more than one container, you should lock them in alphabetically older
Jobs, Monitors, Renders, Users - this is needed to prevent dead lock, if 2 incoming "clients" wants to lock 2 containers at the same time. It is very rare dead lock but it can happen.
 - ops, i already see a bug:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/threadrun.cpp#L76
there is some `lLock` that case bad order
( but dead locks were noticeable when they were locked in process thread in random order at first )

**Comment by timurhai** [comment]
ps
Now i am busy with RULES for my work, so now i am not going to change Afanasy code.
( it is an open-source project tracker, but it is very "inhouse" for now )

**Comment by timurhai** [comment]
Looking more deeper...
 - Server should store task `RUN` state. Now on start it just set all `RUN` tasks to `RDY`. So if some free render registers first, it can take that `RDY` task before reconnected render. (it is not a big deal and i can make it after the merge)
 - Why not just make render to write tasks on register? No new message type and class will be needed, no new network protocol version (simple to upgrade and check).

**Comment by eliemichel** [comment]
1. The mechanism I had in mind at startup was that if a free render gets a task and then an old render claims it, the Task is associated to the later and so the new render will just decide to stop the task (after a host ID mismatch). But this is a little hacky, indeed.

Maybe I got confused with the `Task` + `TaskExec` + `TaskRun` + whatever mechanism and I found it the best way to avoid creating inconsistent states of the server.

I will look at it.

2. I was not sure what was the easiest to upgrade between adding a message type or changing the payload of an existing one. Will change this.

Thanks for the feedback!

**Comment by eliemichel** [comment]
@timurhai I simplified the process and came back to the current master network protocol.
About storing the `RUN` state, should it be done in `TaskData::jsonWrite`?

**Comment by timurhai** [comment]
It should be already done, as web gui knows running tasks. I just remember that afserver on start set all run states to ready.

ps
I continue with all this stuff only at the next week. Have a nice weekend!

pps
I have a birthday tomorrow and so, will be completely unavailable on this holidays :)

**Comment by eliemichel** [comment]
I tried to remove this:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/jobaf.cpp#L257-275

But then it fails with "task is not running errors". I need to investigate further.

ps
No worry, enjoy ;)

**Pull request merged**
