### PR TITLE
Adding function to set job's time-life attribute

### PR DESCRIPTION
**Pull request by abhishekgarg120**

### CODE REVIEW

**Comment by timurhai** [comment]
Great!

**Comment by abhishekgarg120** [comment]
Thanks.

**Comment by timurhai** [comment]
Docs update:
http://cgru.info/afanasy/job#job_time_life

And there was a small mistake )
https://github.com/CGRU/cgru/commit/9ebc1e59cc80065e6440512c2e56c7e1b9959e2f

**Comment by ultra-sonic** [comment]
another awesome feature!

**Pull request merged**
