### PR TITLE
Changed how the Preview commands are listed (images before apps) and real filename instead of "@ARG@".

### PR DESCRIPTION
**Pull request by lithorus**
This is a suggestion on how to list the preview section.

### CODE REVIEW

**Comment by lithorus** [comment]
Example of the changes : 
http://imgur.com/XimvOWO

**Comment by timurhai** [comment]
Hi.
I made replace on launch (not in menu) for cases with a huge length filenames.
But filenames showing in menus can be useful, i agree here.
I think that better to perform some length check and truncate if > 100 characters (for example).
( cut the beginning, for example )

**Comment by lithorus** [comment]
Doesn't it already trunctate?

**Comment by lithorus** [comment]
I mean this line should truncte it :
`QString(cmd).replace("@ARG@", afqt::stoq(files[i]).right(55))`

**Comment by lithorus** [comment]
Regarding truncating and such. Perhaps we should consider to have "aliases" for the files array. Eg :
"test": "/tmp/test.%06d.dpx", "test2": "/tmp/test2.%06d.dpx". That will ofcourse break alot of the current API. Alternatively just trunctate to the last filename.

**Comment by timurhai** [comment]
Oh. I missed it in a hurry, sorry.

**Pull request merged**
