### PR TITLE
Add a JOB_DELETED event

### PR DESCRIPTION
**Pull request by eliemichel**
Add a JOB_DELETED event.
Also abstract a little bit the event emission in JobAf.

Add a simple debug event handler using notify-send instead of events, but since it runs on an arbitrary machine (through the sysjob), it is essentially for debug purpose.

### CODE REVIEW

**Comment by timurhai** [comment]
Ok.
Try to use "i_" prefix for all function arguments (or "o_" or "io_" if they are designed to be changed).
 - or lets discuss it

ps
I know that there are lots of code w/o i_, tabs and spaces are mixed, coding rules were published (and 
tried to be used) just after the project was written :)

**Comment by eliemichel** [comment]
Ah as it is mixed I did not know whether those convention where the old or the new one, so I picked the one I prefered. :D I think that `i_` or `o_` is easy to get depending on whether the argument is `const` (or passed by value), but it's fine, I think it's even more important to follow the convention! Will remember this in the future.

**Comment by eliemichel** [comment]
@timurhai BTW, were are the coding rules? I remember have read them once, but cannot find them again...

(and thx for merging)

**Comment by timurhai** [comment]
They are here:
http://cgru.info/coding_rules

But may be we should have some duplicate there, more closer, on github.
( also i started to use `NULL == ` and recently we decided to use only spaces with Python )

**Comment by eliemichel** [comment]
Ah exact. Yes we could have a copy in the coding tree itself, e.g. in `doc/` or in a `CONTRIBUTING.md`.

**Comment by timurhai** [comment]
Hi.
May be better to emit JOB_DELETED event
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/jobaf.cpp#L304
only if the job and its user has some custom data?
Like it is for JOB_ERROR and JOB_DONE:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/jobaf.cpp#L1086
In our studio in most common cases there is not any custom data.
So on many job deletion at one, afserver spawns lots on dummy tasks (that do nothing, but take a render for some small time).
Or you have some custom `events.py` class that does not need job/user custom data?
May be create some config option, or a job flag for such cases?

**Comment by sebastianelsner** [comment]
I am totally fine with making JOB_DELETED work the same as JOB_DONE (only emit event with custom data). If you have time, I would appreciate the fix.

**Pull request merged**
