### PR TITLE
Implement exceptions for cgruconfig and cgruutils

### PR DESCRIPTION
**Pull request by Kriskras99**
In cgruutils I implemented the exceptions for copy_file(), copyJobFile() and create_folder().
In cgruconfig I added an exception to checkConfigFile and changed the error message.
I also changed the comparison with type() to isinstance(), [rationale](http://docs.quantifiedcode.com/python-anti-patterns/readability/do_not_compare_types_use_isinstance.html)

### CODE REVIEW

**Comment by timurhai** [comment]
Does not work and within Python2 and 3, same error:

timurhai@lu2:/data/cgru/examples/test scripts$ python3 job.py 
Traceback (most recent call last):
  File "job.py", line 10, in <module>
    import af
  File "/data/cgru/afanasy/python/af.py", line 10, in <module>
    import cgruconfig
  File "/data/cgru/lib/python/cgruconfig.py", line 12, in <module>
    import cgruutils
  File "/data/cgru/lib/python/cgruutils.py", line 246, in <module>
    import cgru.config as cgruconfig
ImportError: No module named 'cgru'


timurhai@lu2:/data/cgru/examples/test scripts$ python2 job.py 
Traceback (most recent call last):
  File "job.py", line 10, in <module>
    import af
  File "/data/cgru/afanasy/python/af.py", line 10, in <module>
    import cgruconfig
  File "/data/cgru/lib/python/cgruconfig.py", line 12, in <module>
    import cgruutils
  File "/data/cgru/lib/python/cgruutils.py", line 246, in <module>
    import cgru.config as cgruconfig
ImportError: No module named cgru.config

**Comment by Kriskras99** [comment]
Will fix it right away

Somehow my development branch got mixed in with my master branch. On Mon, Aug 22, 2016 at 11:35 AM, Timur Hairulin < notifications@github.com [notifications@github.com] > wrote:
Does not work and within Python2 and 3, same error:

timurhai@lu2:/data/cgru/examples/test scripts$ python3 job.py
Traceback (most recent call last):
File "job.py", line 10, in
import af
File "/data/cgru/afanasy/python/af.py", line 10, in
import cgruconfig
File "/data/cgru/lib/python/cgruconfig.py", line 12, in
import cgruutils
File "/data/cgru/lib/python/cgruutils.py", line 246, in
import cgru.config as cgruconfig
ImportError: No module named 'cgru'

timurhai@lu2:/data/cgru/examples/test scripts$ python2 job.py
Traceback (most recent call last):
File "job.py", line 10, in
import af
File "/data/cgru/afanasy/python/af.py", line 10, in
import cgruconfig
File "/data/cgru/lib/python/cgruconfig.py", line 12, in
import cgruutils
File "/data/cgru/lib/python/cgruutils.py", line 246, in
import cgru.config as cgruconfig
ImportError: No module named cgru.config

**Comment by timurhai** [comment]
May be simple do like it was before
`import cgruconfig`

Why you need
`import cgru.config as cgruconfig` ?

**Comment by Kriskras99** [comment]
In my dev branch I was looking into making it a normal package (so installed to /usr/lib/python3.5/) and there the package name is cgru.
But somehow I mixed my master and dev branch together.

**Pull request merged**
