### PR TITLE
Initial work for branches in afwatch

### PR DESCRIPTION
**Pull request by lithorus**
Just added the button and the page and the basic skeleton for listing the branches.

### CODE REVIEW

**Comment by lithorus** [comment]
Perhaps better to do the branch list in the jobs tab instead.

**Comment by timurhai** [comment]
Hi.
What do you think about to show branches and their active (not done or offline) jobs in a special monitor, like WebGUI?
WebGUI implementation just started. Later it will show more job info, but less than in Jobs monitor, and GUI element should be smaller. So Branches monitor is designed to show all branches and small brief into about their active jobs. And an ability to perform some (not all) jobs manipulation: change branch, priority, max tasks and some other manipulations that affects jobs solving, as branches are designed for a flexible jobs solving (for example to distribute resources between departments, projects and users, not only users like now)

**Comment by lithorus** [comment]
I was thinking about having a small dropdown in the top part of afwatch. So that you select a branch and see only info within that branch. Perhaps even combined with a project selector.

**Comment by timurhai** [comment]
Hm.
I think that it is useful too.
So we can wait full branches implementation on the server side. than we can start to use it work. And than we can think up some more useful GUI.
For now i need some GUI (and will do it in a WebGUI special monitor) to continue branches server implementation (java-script coding is faster, at least for me).

**Comment by lithorus** [comment]
Sounds like a plan :-) I'll see if I can make some mockups with some ideas. I think branching is really useful.
But perhaps wait with all the GUI stuff (afwatch) until 2.4.0 and have a 2.3.0 release with all the server code in place in the meantime?

**Comment by timurhai** [comment]
Yes, i think too, that it will be so.
For now i can't way when branches will be ready to use.
For now only new node type work-around code is processing (almost finished).
Than i will just start to code solving.

**Comment by lithorus** [comment]
screenshot from 2018-02-21 21-04-38
Added the buttons to the interface (easier than doing a mock up :)). The project selector makes sense to have in the jobs tab only.

**Comment by lithorus** [comment]
Should we discuss this further in an issue instead?

**Comment by timurhai** [comment]
Yes, we will!

**Pull request closed without merging**
