### PR TITLE
The web UI title

### PR DESCRIPTION
**Pull request by eoyilmaz**
* **New:** The web UI title now shows the active job count and the total number of not ``DON`` jobs in the queue and also the total frames in queue that needs to be rendered.

### CODE REVIEW

**Comment by timurhai** [comment]
Hi.
Now i am busy to build 2.3.0 releases.
Just after it i will look at this issue.

**Comment by timurhai** [comment]
Hi.
Why we are removing "var" from a local variables:
https://github.com/CGRU/cgru/pull/419/files#diff-1945e16fedb0b85ca13b23b0d084a694L217
and reformatting this:
https://github.com/CGRU/cgru/pull/419/files#diff-1945e16fedb0b85ca13b23b0d084a694L630
This is some new standard?
If so, we should discuss it first, and create some coding rules:
https://github.com/CGRU/cgru#example

Also even if we a moving on some new formatting, we do not touching old code, just write new with a new format. This way changes history is more clean, and we can see how "old" is code.

**Comment by eoyilmaz** [comment]
I'm using PyCharm to edit the code and it has some "lint" features that warns me about those triple re-declaration of the same variable as being wrong. And as far as I know in JavaScript no matter where you put the declaration it would always be carried to the start of the block (if I'm correctly explaining it). So this was the reason.

And for the reformatting, the world has long moved from TABs to SPACEs and again my IDE was warning me to use Spaces instead of Tabs. So in my first commit I converted them to Spaces but then remembered how much you would like to keep the tabs from my previous commits and then in my next commit I converted them back to Tabs.

> Also even if we a moving on some new formatting, we do not touching old code, just write new with a new format. This way changes history is more clean, and we can see how "old" is code.

I don't see the use of it. Are we writing a history book or developing an always modern code, pardon my pun...

**Comment by timurhai** [comment]
I just refreshed my JS knowledge a little bit :)
**var** - has function scope.
**let** - has block scope, so in that cases, when we want just block scope, we should use **let**
( i just discovered let ! )
But all resources says that we should write
`if (value)` and not `if( value)`

**Comment by eoyilmaz** [comment]
> if (value) and not if( value)

yes I agree and I believe I didn't use that style.

Anyways, I also added fix to Redshift parser to show the progress correctly (it was twice fast, and the render was waiting at 100%, where as it should have been in 50%).

**Comment by eoyilmaz** [comment]
Would you like me to fix anything with this pull request? The Redshift progress fix is kind of a game changer for some.

**Comment by timurhai** [comment]
Hi.
I think we should fix code if some editor highlights some error. And it not the goal, definitely.
If `var` is not a block variable, we should not define all block needed variables in the beginning of a function. If we need a block variable, we should use `let`. We should not write `var i` in the beginning of a function, `i` is a very bad name for such cases. We should use more informative names for a function-global variables. If we need `i` just for `for` block, we should write `for (let i = ...`.
Also what specification tells use to use double quotes in strings?
What specification tell us always to use `===` instead of `==`?
And almost all examples uses `if (condition)`, but your changing it to `if( condition)`.

**Comment by timurhai** [comment]
Also i think that variable scope should be as small as possible.

**Comment by timurhai** [comment]
Hi.
Yes, you reverted `===` to `==` and `"` to `'`.
But can you also revert `var`. You can change it to `let` or i can change it later. The main issue with `var` that you have changed variables scope (desired scope, as i thought that `var` has block scope). `tasks` and `i` were desired block(loop index) variables.

**Comment by timurhai** [comment]
So by "revert `var`" i mean not to place it back, but to revert function scope variables declaration.

**Comment by timurhai** [comment]
Sorry )
I think that now better if i will do what "i mean".

**Comment by timurhai** [comment]
This was that i was talking about
https://github.com/CGRU/cgru/commit/1542dc9f2fc19daa4bc9174bd5afcde5aadfc9f6#diff-1945e16fedb0b85ca13b23b0d084a694R573
( later i will delete that commented line )

**Comment by eoyilmaz** [comment]
Oh ok I got it... Thanks for merging the changes 👍

**Pull request merged**
