### PR TITLE
Adding ``Rez`` support

### PR DESCRIPTION
**Pull request by eoyilmaz**
Modified Houdini, Maya, Blender and Fusion start scripts to make CGRU to work a little easier with ``Rez`` package management system.

So, that if the ``MAYA_LOCATION``, ``HOUDINI_LOCATION``, ``BLENDER_LOCATION`` or ``FUSION_LOCATION`` environment variables are already set before calling the ``start_*`` scripts they will not override it.

This also makes it easier to setup a pipeline which can work with different versions of the software at the same time (as the whole ``rez`` package management system is all about that) without putting ``locate_*`` scripts in to the ``CGRU/software_setup`` folder which is generally not user writable.

### CODE REVIEW

**Comment by eoyilmaz** [comment]
Updated render commands for Maya, Houdini and Blender to use the same ``rez`` environment request with the current running DCC session.

**Comment by timurhai** [comment]
Hi!
So as I see from changes, if someone is not using `res`, all scripts behaviour will be the same as before?

**Comment by eoyilmaz** [comment]
> 

exactly

**Comment by timurhai** [comment]
Great!

**Pull request merged**
