### PR TITLE
Fixes for ``afjob.py`` and ``maya.afanasy``

### PR DESCRIPTION
**Pull request by eoyilmaz**
Fix: Fixed ``afjob.py`` to correctly set ``-proj`` flag for Maya renders.
Fix: Fixed ``maya.afanasy``, setting the ``pwd`` flag is breaking texture search path in Maya Arnold.

### CODE REVIEW

**Comment by timurhai** [comment]
Hi.
I think that we should not use afjob.py from Maya.
Better to use Python API (like afjob.py does) directly within Maya build-in Python.
Python (API) is much more frexible than command line.

ps
When Afanasy appeared, the was no Python in Maya.
Submission scipt was written on MEL, that constructs command line for afjob.
( All soft was on this way, as that time there was no Python in Nuke, Houdini, etc. )
Later almost all soft got Python, submissions were rewritten and begin to use Python API.
Except Maya, MEL was rewritten "on Python", but afjob.py was kept (may be the developer was in a hurry).
Look was afjob.py does, is not it much more simple to do it directly from Maya?

**Comment by eoyilmaz** [comment]
@timurhai ok, I'm updating the job submission script to use the Python API.
@lithorus and I'll remove the code that forces the ``proj`` and ``pwd`` parameters.

**Comment by eoyilmaz** [comment]
Ok done!

Created and merged a PR that has the requested changes.

**Comment by timurhai** [comment]
Great!
Thank you!

**Pull request merged**
