### PR TITLE
Renamed "Preview" to "Launch" in afwatch

### PR DESCRIPTION
**Pull request by lithorus**
The "Preview" submenu label has been renamed to "Launch" to match the
same button in task view. No variables has been renamed/changed.

### CODE REVIEW

**Comment by lithorus** [comment]
I wanted your thoughts on this before merging...

**Comment by timurhai** [comment]
Hi.
"Launch" is more correctly name for developers (TDs), as we launch some command with a filename as argument. But will it be more clear for artists? As commands are designed to view an image file.

**Comment by lithorus** [comment]
My experience is the opposite. The "Preview" option is used for all sorts of things (for instance "publishing" files). But again in the task info window the same button is called "Launch". I think we should atleast have these 2 places using the same word :)

Also since it's now possible to name the tools in Launch/Preview people can make a "Preview in RV" under "Launch".

And another thing worth noting is that "Preview" is also used in another context, when rendering a Pending Preview Approval.

**Comment by timurhai** [comment]
I see. Lets do it!

**Pull request merged**
