### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by eoyilmaz**
Update: Added checks for ``ignore`` settings for Arnold in maya which prompts the user if everything is ok.
Update: Added checks for render camera in Maya, prompts the user if any of the Persp, Side, Top, Right camera is selected as the render camera.
Update: Added Hosts Mask field to Fusion UI
Fix: Fixed Fusion submit script to work with Fusion 6.4+

### CODE REVIEW

**Comment by timurhai** [comment]
Hi. 
All file lines changed:
32ae0c6349d23b3b2348ab7008ea4028556ce8e2

May something with end-of-line? Check your git settings.

btw,
If you are using this script:
https://github.com/CGRU/cgru/blob/master/plugins/maya/afanasy/__init__.py
Much better not to launch any system commands, but use Afanasy Python API.

This script uses it, but take job information from command line arguments:
https://github.com/CGRU/cgru/blob/master/plugins/maya/afanasy/__init__.py#L302

This script was on MEL at first, and was written when Maya has no Python.
Now but more clean and flexible to use Python API directly from a submission script.

Here is a simple example:
http://cgru.info/afanasy/api#python
Also you can check how afjob.py script works:
https://github.com/CGRU/cgru/blob/master/afanasy/python/afjob.py#L886
Python API classes functions are listed here:
http://cgru.info/afanasy/job

**Comment by eoyilmaz** [comment]
I've changed the tabs to spaces which was much easier for me to edit.

Also, as you've suggested, when I've time I will update the Maya job submission script to use the Afanasy Python API which seems to be much more convenient to use then the command line version.

**Comment by timurhai** [comment]
So, are you going to switch it back to tabs?
Or we can keep spaces in "your" files.
But in this case project will have various indentation ways (for me it is not a big problem).

**Comment by eoyilmaz** [comment]
I would love to have all Python files to follow PEP8 (
https://www.python.org/dev/peps/pep-0008/#id13) rules in which most of the
IDEs around are working well with.

**Comment by mifth** [comment]
Pycharm uses spaces y default. Also, Blender scripts use spaces too.
I woul make all in spaces.

**Comment by timurhai** [comment]
Ok!
Lets use only spaces for python, as it uses indentation for code blocks.

**Pull request merged**
