### PR TITLE
Add an entry to render ctx menu to access running task

### PR DESCRIPTION
**Pull request by eliemichel**
It opens the task dialog for the running task.
As #231 suggest, it would be nice if this dialog could enable the user to perform actions on the task.

### CODE REVIEW

**Comment by timurhai** [comment]
Remember, after such parameters writing order change, we loose backward compatibility.
https://github.com/CGRU/cgru/pull/237/files#diff-fbe20c2a3c390aa9ee53109d4db84d56R231

But, it seems that we already lost it here:
https://github.com/CGRU/cgru/commit/d245432b016482ed2db5f9bd88d88673da86ccb9#diff-b772bea76851a1021b9e467549e507e3R208

Now we should change network protocol version number, and can change version.txt to 2.2.0
( as it is compatible with 2.1.0 )

**Comment by eliemichel** [comment]
Ah sorry, I forgot that I had "momentarily" .gitignored version.h...

**Comment by lithorus** [comment]
How does this handle multiple running tasks on the render host? One entry
per task?

**Comment by timurhai** [comment]
This can be a solution, i think:
 - if tasks > 1:
RMB menu -> Tasks submenu -> TaskName submenu -> Actions menuitems
 - if tasks == 1:
RMB menu -> Task submenu -> Actions menuitems
- if tasks == 0:
No Task(s) submenu.

**Comment by eliemichel** [comment]
@lithorus For now there is a submenu listing all the running tasks, so it handles it well, but the solution proposed by @timurhai sounds even nicer.

**Comment by timurhai** [comment]
Such functions can be static:
https://github.com/CGRU/cgru/blob/master/afanasy/src/watch/listtasks.cpp#L543
IDs can be provided by arguments.
This way we can use the same code to execute actions.

And if we use `ActionIdIdId` in  `ListTasks` too, may be we can even reuse code that creating actions menu items.

**Comment by lithorus** [comment]
I thought the running task menu was about the task output. This is usually what you want to dig out when debugging why a render node is stalling or taking so long time.

**Comment by eliemichel** [comment]
This is also my need in the end.

It will be possible to get the task output if we follow @timurhai 's suggestion to put a full task context menu for each task in the list, instead of just a button to open the task window.

My way to go, as shown in #231, was more to make everything accessible from the task window. But I would understand that too many spawning windows can be annoying.

**Comment by lithorus** [comment]
Which brings me to another topic.
With all these right click options it can be quite difficult to get an overview. Perhaps it's time to think about a reworked interface, more a'la Deadline with everything in 1 window?

**Comment by eliemichel** [comment]
This is why I suggested to at least have a copy of these context menu actions in the task window. Docking the task window itself to avoid poping up many is a next step. But this would be a huge change...

**Comment by timurhai** [comment]
Not so huge.
One watch already can show and jobs and jobs and users (RMB menu on main buttons).
We can make him to open them in the same window.

But all such changes should be customizeable. Most users(aritst) just watch its jobs running, they know (and does not want to know) about renders and tasks. Also renders and tasks windows are much more "heavy" for traffic and server load. If all users will see everything we will increase load about 10 times, and will show info that does not needed and even can divert common artists.

So this UI is enough for artist by default (and was specially designed for it).
But i agree that for TDs (render wranglers) can be useful to have all Afanasy stuff in 1 window, as usually such people already have to open lots of other windows even w/o Afanasy.

**Comment by predat** [comment]
I'm totally agree with @lithorus. As i sais in this comment: https://github.com/CGRU/cgru/issues/193#issuecomment-199372500

One window for watch would be more efficient !

**Comment by eliemichel** [comment]
@lithorus You can now (since ea6017b) access the task output through right click on renders, though only the current one, not the history of outputs.

**Pull request merged**
