### PR TITLE
Renamed the override.sh to override_maya.sh

### PR DESCRIPTION
**Pull request by eoyilmaz**
* [Maya] Renamed the ``override.cmd`` and ``override.sh`` calls to ``override_maya.cmd`` and ``override_maya.sh`` to remove the ambiguity (other programs can have overrides too).

### CODE REVIEW

**Comment by timurhai** [comment]
Hi!
May be better to keep both lines?
`
IF EXIST override.cmd CALL override.cmd
IF EXIST override_maya.cmd CALL override_maya.cmd
`
This way we will keep backwards compatibility.

**Comment by eoyilmaz** [comment]
Sure, I'll update my pull request :+1:

**Comment by eoyilmaz** [comment]
Added back the ``override.sh/cmd`` calls :+1:

**Comment by eoyilmaz** [comment]
Oh also another commit has sneaked in, sorry for that. I've updated the ``start_blender.sh/.cmd`` for Blender 2.82+ to see the PYTHONPATH environment variable on start. You see, there was a change in how Blender handles the PYTHONPATH environment variable and without the ``--python-use-system-env`` argument Blender don't use the PYTHONPATH env var. This commit fixes that.

**Comment by timurhai** [comment]
Great!

**Pull request merged**
