### PR TITLE
New job properties

### PR DESCRIPTION
**Pull request by eliemichel**
Add a `project` property to jobs.

Other properties to come in the PR are a `department` property (`compositing`, `modeling`, etc.) and a proper implementation of the `no-progress-for` feature that we currently implement using custom properties.

afanasy-project-property

_A job w/o and w/ project property attached (project name is `afanasy-dev` here)._

### CODE REVIEW

**Comment by timurhai** [comment]
For now, `project` and `department` are properties to display in GUI only?
Later you have some plans for this? May be solve by project / department?

`no-progress-for` is just for gui for not too? I can't see that it changes anywhere, just on submission in Python API?

**Comment by sebastianelsner** [comment]
yes, they will be displayed in the ui only for now, but filtering in the monitors would be good.

the no-progress-for functionality is coming soon. the logic will be in the parser: If there was no progress for X time, the task is canceled.

**Comment by timurhai** [comment]
Hm.
In this case it should a block parameter, to be able to differ it for other task types.
And called `task_progress_change_timeout` or somehow with "task" in the name.
As at first i did not got it.
What do you think?

btw
Also some task progress parameter should be added here:
https://github.com/CGRU/cgru/blob/master/afanasy/src/libafanasy/taskprogress.h#L29
something like "time_prgress" and on block refresh it should restart it (and log it).
Or are you going to implement it?

**Comment by eliemichel** [comment]
* `project` and `department` are just for displaying and sorting for now.

 * I will move the `no-progress-for` stuff in another branch so that this one will just be about adding simple properties.

 * Yes, it would be better to call it `task_progress_change_timeout`.

 * Did not really got your last point. ^^

**Comment by timurhai** [comment]
Ah, i remember.
If you are going to restart it from parser, you do not need to implement it block.cpp.
But if you already going to add this parameter it is not a big deal to make server to restart it.

**Comment by sebastianelsner** [comment]
> But if you already going to add this parameter it is not a big deal to make server to restart it.

what do you mean by "restart it". that is the current behaviour we are using: terminate task and requeue it.

**Comment by timurhai** [comment]
Yes, i mean the same )

**Comment by eliemichel** [comment]
@timurhai I removed no-prog-for from this branch, it is now only about `project` and `department` and displaying job ID in afwatch.
Will open another branch (but no PR yet) for no prog for.

**Pull request merged**
