### PR TITLE
Add Pause mode to renders

### PR DESCRIPTION
**Pull request by eliemichel**
Pause mode, a.k.a. super-nimby, is a nimby-like mode that will not be
automatically deactivated with idle time.
It is accessible in GOD mode only.

### CODE REVIEW

**Comment by timurhai** [comment]
Hi.
It is a useful feature, it really needed, but there is already `nimby` and `NIMBY` modes, now `super_nimby` added, may be just call it paused? Like you already doing it in guis, outputs, and this issue?
btw
Why did you removed hide-unhide render from afwatch?

**Comment by eliemichel** [comment]
Mmh my point in calling it `super_nimby` on the code side was that its mechanism is really close to `nimby`/`NIMBY` modes. So if one eventually refactors `nimby`/`NIMBY`, it would be good to refactor `super_nimby` at the same time, which may be forgotten if it is named `paused` that sounds different.

But, fair enough, @sebastianelsner didn't like it neither so I will rename it `paused`!

About hide/unhide, it was commented out and seemed not connected to anything, so I though it was legacy code. I believe that when using a versionning system such as git, commented out code should almost never exist in committed code.

**Comment by timurhai** [comment]
Hm, i forgot why hide/unhide was hidden - my fault, i should place more code comments )

Why this pull request changes XSI python files?

**Comment by eliemichel** [comment]
Because of the last commit, "Sync with current master", that fixes some merging conflict.
I can revert it if you prefer doing the merge yourself.

**Comment by timurhai** [comment]
Lets give them some other (not `nimby`) color, gray, for example.

**Pull request merged**
